language: csharp
solution: University.sln
mono: none
dotnet: 3.1
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - NET_CORE_VERSION: netcoreapp3.1
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      dotnet: 3.1.100
      osx_image: xcode10.2
script:
  - dotnet restore
  - dotnet test "University.Tests/University.Tests.csproj" --configuration Release --framework "$NET_CORE_VERSION"
